// Excluded: KPW (North Korea), IRR (Iran), SYP (Syria) — under UN/Malaysian sanctions.
class AppCurrency {
  const AppCurrency(this.code, this.name);

  final String code;
  final String name;

  static AppCurrency? find(String code) =>
      all.where((c) => c.code == code).firstOrNull;

  static String nameFor(String code) => find(code)?.name ?? code;

  static const List<AppCurrency> all = [
    AppCurrency('AFN', 'Afghan Afghani'),
    AppCurrency('ALL', 'Albanian Lek'),
    AppCurrency('DZD', 'Algerian Dinar'),
    AppCurrency('AOA', 'Angolan Kwanza'),
    AppCurrency('ARS', 'Argentine Peso'),
    AppCurrency('AMD', 'Armenian Dram'),
    AppCurrency('AWG', 'Aruban Florin'),
    AppCurrency('AUD', 'Australian Dollar'),
    AppCurrency('AZN', 'Azerbaijani Manat'),
    AppCurrency('BSD', 'Bahamian Dollar'),
    AppCurrency('BHD', 'Bahraini Dinar'),
    AppCurrency('BDT', 'Bangladeshi Taka'),
    AppCurrency('BBD', 'Barbadian Dollar'),
    AppCurrency('BYN', 'Belarusian Ruble'),
    AppCurrency('BZD', 'Belize Dollar'),
    AppCurrency('BMD', 'Bermudian Dollar'),
    AppCurrency('BTN', 'Bhutanese Ngultrum'),
    AppCurrency('BOB', 'Bolivian Boliviano'),
    AppCurrency('BAM', 'Bosnia-Herzegovina Convertible Mark'),
    AppCurrency('BWP', 'Botswana Pula'),
    AppCurrency('BRL', 'Brazilian Real'),
    AppCurrency('BND', 'Brunei Dollar'),
    AppCurrency('BGN', 'Bulgarian Lev'),
    AppCurrency('BIF', 'Burundian Franc'),
    AppCurrency('CVE', 'Cape Verdean Escudo'),
    AppCurrency('KHR', 'Cambodian Riel'),
    AppCurrency('CAD', 'Canadian Dollar'),
    AppCurrency('KYD', 'Cayman Islands Dollar'),
    AppCurrency('XAF', 'Central African CFA Franc'),
    AppCurrency('CLP', 'Chilean Peso'),
    AppCurrency('CNY', 'Chinese Yuan'),
    AppCurrency('COP', 'Colombian Peso'),
    AppCurrency('KMF', 'Comorian Franc'),
    AppCurrency('CDF', 'Congolese Franc'),
    AppCurrency('CRC', 'Costa Rican Colón'),
    AppCurrency('CUP', 'Cuban Peso'),
    AppCurrency('CZK', 'Czech Koruna'),
    AppCurrency('DKK', 'Danish Krone'),
    AppCurrency('DJF', 'Djiboutian Franc'),
    AppCurrency('DOP', 'Dominican Peso'),
    AppCurrency('EGP', 'Egyptian Pound'),
    AppCurrency('ERN', 'Eritrean Nakfa'),
    AppCurrency('ETB', 'Ethiopian Birr'),
    AppCurrency('EUR', 'Euro'),
    AppCurrency('FJD', 'Fijian Dollar'),
    AppCurrency('GMD', 'Gambian Dalasi'),
    AppCurrency('GEL', 'Georgian Lari'),
    AppCurrency('GHS', 'Ghanaian Cedi'),
    AppCurrency('GBP', 'British Pound Sterling'),
    AppCurrency('GTQ', 'Guatemalan Quetzal'),
    AppCurrency('GNF', 'Guinean Franc'),
    AppCurrency('GYD', 'Guyanese Dollar'),
    AppCurrency('HTG', 'Haitian Gourde'),
    AppCurrency('HNL', 'Honduran Lempira'),
    AppCurrency('HKD', 'Hong Kong Dollar'),
    AppCurrency('HUF', 'Hungarian Forint'),
    AppCurrency('ISK', 'Icelandic Króna'),
    AppCurrency('INR', 'Indian Rupee'),
    AppCurrency('IDR', 'Indonesian Rupiah'),
    AppCurrency('IQD', 'Iraqi Dinar'),
    AppCurrency('ILS', 'Israeli New Shekel'),
    AppCurrency('JMD', 'Jamaican Dollar'),
    AppCurrency('JPY', 'Japanese Yen'),
    AppCurrency('JOD', 'Jordanian Dinar'),
    AppCurrency('KZT', 'Kazakhstani Tenge'),
    AppCurrency('KES', 'Kenyan Shilling'),
    AppCurrency('KWD', 'Kuwaiti Dinar'),
    AppCurrency('KGS', 'Kyrgystani Som'),
    AppCurrency('LAK', 'Laotian Kip'),
    AppCurrency('LBP', 'Lebanese Pound'),
    AppCurrency('LSL', 'Lesotho Loti'),
    AppCurrency('LRD', 'Liberian Dollar'),
    AppCurrency('LYD', 'Libyan Dinar'),
    AppCurrency('MOP', 'Macanese Pataca'),
    AppCurrency('MGA', 'Malagasy Ariary'),
    AppCurrency('MWK', 'Malawian Kwacha'),
    AppCurrency('MYR', 'Malaysian Ringgit'),
    AppCurrency('MVR', 'Maldivian Rufiyaa'),
    AppCurrency('MRU', 'Mauritanian Ouguiya'),
    AppCurrency('MUR', 'Mauritian Rupee'),
    AppCurrency('MXN', 'Mexican Peso'),
    AppCurrency('MDL', 'Moldovan Leu'),
    AppCurrency('MNT', 'Mongolian Tögrög'),
    AppCurrency('MAD', 'Moroccan Dirham'),
    AppCurrency('MZN', 'Mozambican Metical'),
    AppCurrency('MMK', 'Myanmar Kyat'),
    AppCurrency('NAD', 'Namibian Dollar'),
    AppCurrency('NPR', 'Nepalese Rupee'),
    AppCurrency('NZD', 'New Zealand Dollar'),
    AppCurrency('NIO', 'Nicaraguan Córdoba'),
    AppCurrency('NGN', 'Nigerian Naira'),
    AppCurrency('NOK', 'Norwegian Krone'),
    AppCurrency('OMR', 'Omani Rial'),
    AppCurrency('PKR', 'Pakistani Rupee'),
    AppCurrency('PGK', 'Papua New Guinean Kina'),
    AppCurrency('PYG', 'Paraguayan Guaraní'),
    AppCurrency('PEN', 'Peruvian Sol'),
    AppCurrency('PHP', 'Philippine Peso'),
    AppCurrency('PLN', 'Polish Złoty'),
    AppCurrency('QAR', 'Qatari Riyal'),
    AppCurrency('RON', 'Romanian Leu'),
    AppCurrency('RUB', 'Russian Ruble'),
    AppCurrency('RWF', 'Rwandan Franc'),
    AppCurrency('WST', 'Samoan Tālā'),
    AppCurrency('SAR', 'Saudi Riyal'),
    AppCurrency('RSD', 'Serbian Dinar'),
    AppCurrency('SCR', 'Seychellois Rupee'),
    AppCurrency('SLL', 'Sierra Leonean Leone'),
    AppCurrency('SGD', 'Singapore Dollar'),
    AppCurrency('SBD', 'Solomon Islands Dollar'),
    AppCurrency('SOS', 'Somali Shilling'),
    AppCurrency('ZAR', 'South African Rand'),
    AppCurrency('SSP', 'South Sudanese Pound'),
    AppCurrency('LKR', 'Sri Lankan Rupee'),
    AppCurrency('SDG', 'Sudanese Pound'),
    AppCurrency('SRD', 'Surinamese Dollar'),
    AppCurrency('SZL', 'Swazi Lilangeni'),
    AppCurrency('SEK', 'Swedish Krona'),
    AppCurrency('CHF', 'Swiss Franc'),
    AppCurrency('TWD', 'New Taiwan Dollar'),
    AppCurrency('TZS', 'Tanzanian Shilling'),
    AppCurrency('THB', 'Thai Baht'),
    AppCurrency('TOP', 'Tongan Paʻanga'),
    AppCurrency('TTD', 'Trinidad and Tobago Dollar'),
    AppCurrency('TND', 'Tunisian Dinar'),
    AppCurrency('TRY', 'Turkish Lira'),
    AppCurrency('TMT', 'Turkmenistani Manat'),
    AppCurrency('UGX', 'Ugandan Shilling'),
    AppCurrency('UAH', 'Ukrainian Hryvnia'),
    AppCurrency('AED', 'UAE Dirham'),
    AppCurrency('USD', 'US Dollar'),
    AppCurrency('UYU', 'Uruguayan Peso'),
    AppCurrency('UZS', 'Uzbekistani Som'),
    AppCurrency('VUV', 'Vanuatu Vatu'),
    AppCurrency('VES', 'Venezuelan Bolívar'),
    AppCurrency('VND', 'Vietnamese Đồng'),
    AppCurrency('XOF', 'West African CFA Franc'),
    AppCurrency('XPF', 'CFP Franc'),
    AppCurrency('YER', 'Yemeni Rial'),
    AppCurrency('ZMW', 'Zambian Kwacha'),
    AppCurrency('ZWL', 'Zimbabwean Dollar'),
  ];
}
